hello_world
SageOfDev/DjangoExercise pull request #1
Opened 2022-03-17 06:06 UTC by SageOfDev

2022-03-17 09:52 UTC, ycice requested changes
장고를 잘 모르긴 하는데 이게 완성인가요?
일단 run.py 같은 실행파일이 없네요? port도 지정하고 그럴려면 뭔가 다른 파일이 필요해보입니다
view.py를 작동시키는건 아닐것같고

그리고 veiw.py에 보통 app.route('/') 뭐 이런식으로 해서 어떤 주소로 올때 어떤 웹페이지를 띄워줄지 routing 역할을 하는 코드가 있어야될것같은데..

2022-03-17 09:52 UTC, ycice commented on DjangoExercise/urls.py
> +from .views import hello_world
views 가 아니라 .views 로 하면 어떤 차이가 있나요?

2022-03-17 09:52 UTC, ycice commented on DjangoExercise/urls.py
> +    path('', hello_world),
이 path 의 역할은 뭔가요

2022-03-18 06:29 UTC, SageOfDev commented on DjangoExercise/urls.py
> +from .views import hello_world
> views 가 아니라 .views 로 하면 어떤 차이가 있나요?

from views는 views라는 모듈을 라이브러리 혹은 프로젝트 root 폴더에서 찾습니다.
from .views는 현재 폴더에서 views라는 모듈을 찾습니다. .은 현재 폴더를 의미합니다.

2022-03-18 06:32 UTC, SageOfDev commented on DjangoExercise/urls.py
> +    path('', hello_world),
> 이 path 의 역할은 뭔가요

도메인뿐인 url을 hello_world라는 view function에 연결해주는 설정 역할을 해줍니다.

2022-03-18 06:41 UTC, SageOfDev commented on DjangoExercise/urls.py
> +from .views import hello_world
> 장고를 잘 모르긴 하는데 이게 완성인가요? 일단 run.py 같은 실행파일이 없네요? port도 지정하고 그럴려면 뭔가 다른 파일이 필요해보입니다 view.py를 작동시키는건 아닐것같고

/DjangoExercise/manage.py 이 실행파일이라고 알고 있습니다.
CLI에서 가상환경을 activate한 후 DjangoExercise 디렉터리에서
`python manage.py runserver <포트>`
명령을 입력하면 원하는 포트로 실행할 수 있습니다.

djnago에서 실행파일을 커스텀해서 만드는 것은 찾아보았지만, 아직 적당한 문헌을 발견하지 못했습니다.


> 그리고 veiw.py에 보통 app.route('/') 뭐 이런식으로 해서 어떤 주소로 올때 어떤 웹페이지를 띄워줄지 routing 역할을 하는 코드가 있어야될것같은데..

url 설정은 urls.py에서 담당합니다.
예를 들어
```
urlpatterns = [
    path('', hello_world),
]
```
은 `http://www.<DomainName>/' 라는 url을 hello_world라는 view function으로 연결해줍니다.

2022-03-18 10:56 UTC, ycice approved these changes

2022-03-18 11:14 UTC, merged